# Default values for json-server
replicaCount: 1

image:
  repository: local/json-server
  tag: "0.17.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

minio:
  mode: "standalone"
  replicas: 1
  persistence:
    enabled: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
  enabled: true
  bucket: "json-data"
  file: "db.json"
  accessKey: ""
  secretKey: ""

initContainer:
  image: minio/mc
