# Default values for json-server
replicaCount: 1

image:
  repository: typicode/json-server
  tag: "0.17.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

minio:
  enabled: true
  bucket: "json-data"
  file: "db.json"
  accessKey: ""
  secretKey: ""

initContainer:
  image: minio/mc
  command: ["sh", "-c", "mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} && mc cp minio/${MINIO_BUCKET}/${MINIO_FILE} /data/db.json"]
