apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  labels:
    {{- include "json-server.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.minio.accessKey | b64enc | quote }}
  secretKey: {{ .Values.minio.secretKey | b64enc | quote }}
